#!/bin/bash

export PATH=/home/slyeung/Downloads/toolchain/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin:$PATH

export CC=arm-linux-gnueabihf-gcc

make -f scan_finger.mak clean
make -f scan_finger.mak

